(()=>{
const cfg=window.APP_CONFIG;const $=id=>document.getElementById(id);const els={};['loginView','appView','parentView','workerView','loginForm','caseCode','displayName','accessPin','loginMsg','logoutBtn','roleLabel','welcome','caseLabel','onlineDot','networkStatus','visitStatus','visitStatusSub','visitTimer','myCheckins','nextDue','accuracy','startVisitBtn','gpsBtn','virtualBtn','videoCheckBtn','note','checkMsg','parentCallTarget','workerCallTarget','parentCallBtn','workerCallBtn','parentHistory','workerHistory','parentRange','workerRange','parentCount','activeVisits','readyReviews','completedVisits','visitCards','refreshBtn','turnBadge','installBtn','installDialog','installSteps','deviceBtn','deviceDialog','preview','switchCam','deviceMsg','callDialog','callTitle','callState','remoteVideo','localVideo','micBtn','camBtn','hangupBtn','callMsg','incomingDialog','incomingName','declineBtn','acceptBtn','reviewDialog','reviewSummary','reviewNote','markNon','markCompliant','reviewMsg'].forEach(x=>els[x]=$(x));
let role='parent',token=sessionStorage.getItem('fvc_token')||'',user=null,caseInfo=null,members=[],dashboard={visits:[],checkins:[]},activeVisit=null,socket=null,iceServers=[],pc=null,callStream=null,currentPeer=null,currentCallId=null,pendingCall=null,deviceStream=null,facing='user',reviewVisitId=null,timerId=null,deferredInstall=null;
const api=async(path,opt={})=>{const r=await fetch(cfg.API_URL+path,{...opt,headers:{'Content-Type':'application/json',...(token?{Authorization:`Bearer ${token}`}:{ }),...(opt.headers||{})}});const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error||`Request failed ${r.status}`);return j};
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const fmt=d=>new Intl.DateTimeFormat([], {dateStyle:'medium',timeStyle:'short'}).format(new Date(d));
const mins=n=>`${Math.max(0,Math.round(n))} min`;

document.querySelectorAll('[data-role]').forEach(b=>b.onclick=()=>{role=b.dataset.role;document.querySelectorAll('[data-role]').forEach(x=>x.classList.toggle('active',x===b));});
els.loginForm.onsubmit=async e=>{e.preventDefault();els.loginMsg.textContent='Checking access…';try{const j=await api('/api/login',{method:'POST',body:JSON.stringify({caseCode:els.caseCode.value.trim(),role,displayName:els.displayName.value.trim(),pin:els.accessPin.value})});token=j.token;sessionStorage.setItem('fvc_token',token);setIdentity(j);await enterApp();}catch(err){els.loginMsg.textContent=err.message;}};
els.logoutBtn.onclick=()=>{sessionStorage.removeItem('fvc_token');location.reload()};
async function boot(){try{const c=await fetch(cfg.API_URL+'/api/public-config').then(r=>r.json());iceServers=c.iceServers||[];els.turnBadge.textContent=c.turnConfigured?'TURN relay ready':'Direct calling';els.turnBadge.className='badge '+(c.turnConfigured?'good':'warn');}catch{els.turnBadge.textContent='RTC config unavailable';}if(token){try{const j=await api('/api/me');setIdentity(j);await enterApp();}catch{sessionStorage.removeItem('fvc_token');token='';}}setupInstall();if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});}
function setIdentity(j){user=j.user;caseInfo=j.case;members=j.members||[];}
async function enterApp(){els.loginView.classList.add('hidden');els.appView.classList.remove('hidden');els.logoutBtn.classList.remove('hidden');els.roleLabel.textContent=user.role==='parent'?'PARENT PORTAL':'CASEWORKER PORTAL';els.welcome.textContent=`Welcome, ${user.display_name}`;els.caseLabel.textContent=`${caseInfo.label} • Case ${caseInfo.case_code} • ${caseInfo.visit_minutes||120}-minute visits`;els.parentView.classList.toggle('hidden',user.role!=='parent');els.workerView.classList.toggle('hidden',user.role!=='caseworker');populateCalls();connectSocket();await refresh();timerId=setInterval(renderTimers,1000);}
function populateCalls(){const p=members.filter(m=>m.role==='parent'&&m.id!==user.id),w=members.filter(m=>m.role==='caseworker'&&m.id!==user.id);els.parentCallTarget.innerHTML='<option value="">Select caseworker</option>'+w.map(x=>`<option value="${x.id}">${esc(x.display_name)}</option>`).join('');els.workerCallTarget.innerHTML='<option value="">Select parent</option>'+p.map(x=>`<option value="${x.id}">${esc(x.display_name)}</option>`).join('');}
async function refresh(){const j=await api(`/api/case/${caseInfo.id}/dashboard`);dashboard=j;activeVisit=dashboard.visits.find(v=>v.status==='active')||null;render();}
function render(){if(user.role==='parent')renderParent();else renderWorker();renderTimers();}
function rangeDays(v){return v==='all'?Infinity:Number(v)}
function inRange(ts,days){return days===Infinity||Date.now()-new Date(ts).getTime()<=days*864e5}
function renderParent(){const mine=dashboard.checkins.filter(c=>c.parent_id===user.id);const activeMine=activeVisit?mine.filter(c=>c.visit_id===activeVisit.id):[];els.visitStatus.textContent=activeVisit?'Active':(dashboard.visits[0]?.status?dashboard.visits[0].status.replace('_',' '):'Not started');els.visitStatusSub.textContent=activeVisit?`Started ${fmt(activeVisit.started_at)}`:'Start when your visit begins';els.myCheckins.textContent=activeMine.length;const lastGps=mine.find(c=>c.accuracy_m!=null);els.accuracy.textContent=lastGps?`±${Math.round(lastGps.accuracy_m)} m`:'—';[els.gpsBtn,els.virtualBtn,els.videoCheckBtn].forEach(b=>b.disabled=!activeVisit);const days=rangeDays(els.parentRange.value);const visits=Object.fromEntries(dashboard.visits.map(v=>[v.id,v]));els.parentHistory.innerHTML=mine.filter(c=>inRange(c.created_at,days)).map(c=>`<tr><td>${fmt(visits[c.visit_id]?.started_at||c.created_at)}</td><td>${fmt(c.created_at)}</td><td>${esc(c.method)}</td><td>${c.accuracy_m!=null?`±${Math.round(c.accuracy_m)} m`:'—'}</td><td>${esc((visits[c.visit_id]?.status||'active').replace('_',' '))}</td></tr>`).join('')||'<tr><td colspan="5">No check-ins in this period.</td></tr>';}
function renderWorker(){const parents=members.filter(m=>m.role==='parent');els.parentCount.textContent=parents.length;els.activeVisits.textContent=dashboard.visits.filter(v=>v.status==='active').length;els.readyReviews.textContent=dashboard.visits.filter(v=>v.status==='active'&&v.review_ready).length;els.completedVisits.textContent=dashboard.visits.filter(v=>v.status!=='active').length;els.visitCards.innerHTML=dashboard.visits.slice(0,12).map(v=>{const checks=dashboard.checkins.filter(c=>c.visit_id===v.id),byParent=parents.map(p=>({p,c:checks.filter(c=>c.parent_id===p.id)})).filter(x=>x.c.length);return `<div class="visit-card"><div class="row"><div><h4>${fmt(v.started_at)}</h4><small>${checks.length} total check-in${checks.length===1?'':'s'} • ends ${fmt(v.ends_at)}</small></div><span class="badge ${v.status==='compliant'?'good':v.status==='non_compliant'?'bad':v.review_ready?'warn':''}">${esc(v.status.replace('_',' '))}</span></div><ul class="check-list">${byParent.map(x=>`<li><b>${esc(x.p.display_name)}</b> — ${x.c.length} check-in${x.c.length===1?'':'s'} ${x.c.map(c=>`#${c.checkin_number} ${esc(c.method)}`).join(' · ')}</li>`).join('')||'<li>No check-ins yet</li>'}</ul>${v.status==='active'?`<button class="${v.review_ready?'primary':'ghost'} wide review-btn" data-id="${v.id}" ${v.review_ready?'':'disabled'}>${v.review_ready?'Finalize visit':'Waiting for second check-in'}</button>`:`<a class="ghost report-link" href="${cfg.API_URL}/api/case/${caseInfo.id}/visit/${v.id}/report.pdf" data-report="${v.id}">Download report</a>`}</div>`}).join('')||'<div class="muted">No visits recorded yet.</div>';document.querySelectorAll('.review-btn').forEach(b=>b.onclick=()=>openReview(b.dataset.id));document.querySelectorAll('[data-report]').forEach(a=>a.onclick=downloadReport);const days=rangeDays(els.workerRange.value),byId=Object.fromEntries(members.map(m=>[m.id,m]));els.workerHistory.innerHTML=dashboard.checkins.filter(c=>inRange(c.created_at,days)).map(c=>`<tr><td>${esc(byId[c.parent_id]?.display_name||'Parent')}</td><td>${fmt(dashboard.visits.find(v=>v.id===c.visit_id)?.started_at||c.created_at)}</td><td>${fmt(c.created_at)}</td><td>${esc(c.method)}</td><td>${c.latitude!=null?`${c.latitude.toFixed(5)}, ${c.longitude.toFixed(5)} (±${Math.round(c.accuracy_m||0)}m)`:'—'}</td></tr>`).join('')||'<tr><td colspan="5">No check-ins in this period.</td></tr>';}
function renderTimers(){if(!activeVisit){els.visitTimer.textContent='2:00:00';els.nextDue.textContent='No active visit';return;}const remain=Math.max(0,new Date(activeVisit.ends_at)-Date.now());const h=Math.floor(remain/36e5),m=Math.floor(remain%36e5/6e4),s=Math.floor(remain%6e4/1000);els.visitTimer.textContent=`${h}:${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`;const mine=dashboard.checkins.filter(c=>c.visit_id===activeVisit.id&&c.parent_id===user.id);const base=mine.length?new Date(mine[mine.length-1].created_at).getTime():new Date(activeVisit.started_at).getTime();const due=base+(caseInfo.checkin_interval_minutes||45)*60000;const delta=(due-Date.now())/60000;els.nextDue.textContent=delta>0?`Next check-in in ${mins(delta)}`:`Check-in due ${mins(-delta)} ago`;}
els.startVisitBtn.onclick=async()=>{try{const j=await api(`/api/case/${caseInfo.id}/visit/start`,{method:'POST',body:'{}'});activeVisit=j.visit;await refresh();flash('Visit started/joined. Your first check-in can be submitted now.');}catch(e){flash(e.message,true)}};
els.gpsBtn.onclick=()=>navigator.geolocation?navigator.geolocation.getCurrentPosition(p=>submitCheck('location',{latitude:p.coords.latitude,longitude:p.coords.longitude,accuracy:p.coords.accuracy}),e=>flash(`Location unavailable: ${e.message}`,true),{enableHighAccuracy:true,timeout:15000,maximumAge:0}):flash('This browser does not support location.',true);
els.virtualBtn.onclick=()=>submitCheck('virtual',{});els.videoCheckBtn.onclick=async()=>{await openDevice(true);if(deviceStream)submitCheck('video',{});};
async function submitCheck(method,extra){try{const j=await api(`/api/case/${caseInfo.id}/checkin`,{method:'POST',body:JSON.stringify({visitId:activeVisit.id,method,note:els.note.value.trim(),...extra})});els.note.value='';flash(`${method==='location'?'Location':'Check-in'} #${j.checkin.checkin_number} recorded at ${fmt(j.checkin.created_at)}.${j.reviewReady?' The visit is now eligible for caseworker review.':''}`);await refresh();}catch(e){flash(e.message,true)}}
function flash(s,bad=false){els.checkMsg.classList.remove('hidden');els.checkMsg.style.background=bad?'#fee4e2':'#eefbf4';els.checkMsg.style.color=bad?'#b42318':'#137a4d';els.checkMsg.textContent=s;}
els.parentRange.onchange=renderParent;els.workerRange.onchange=renderWorker;els.refreshBtn.onclick=refresh;
function openReview(id){reviewVisitId=id;const v=dashboard.visits.find(x=>x.id===id),cs=dashboard.checkins.filter(x=>x.visit_id===id);els.reviewSummary.textContent=`Visit started ${fmt(v.started_at)} with ${cs.length} submitted check-ins. Choose the final caseworker determination.`;els.reviewNote.value='';els.reviewMsg.textContent='';els.reviewDialog.showModal();}
els.markCompliant.onclick=()=>finalize('compliant');els.markNon.onclick=()=>finalize('non_compliant');async function finalize(outcome){els.reviewMsg.textContent='Finalizing and preparing supervisor report…';try{const j=await api(`/api/case/${caseInfo.id}/visit/${reviewVisitId}/review`,{method:'POST',body:JSON.stringify({outcome,note:els.reviewNote.value.trim()})});els.reviewMsg.textContent=`Recorded as ${outcome.replace('_',' ')}. Supervisor delivery: ${j.reportDelivery.status}.`;await refresh();setTimeout(()=>els.reviewDialog.close(),1200);}catch(e){els.reviewMsg.textContent=e.message;}}
async function downloadReport(e){e.preventDefault();const id=e.currentTarget.dataset.report;try{const r=await fetch(`${cfg.API_URL}/api/case/${caseInfo.id}/visit/${id}/report.pdf`,{headers:{Authorization:`Bearer ${token}`}});if(!r.ok)throw new Error('Could not download report');const blob=await r.blob(),u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=`visit-${id}.pdf`;a.click();setTimeout(()=>URL.revokeObjectURL(u),5000);}catch(err){alert(err.message)}}
function connectSocket(){socket=io(cfg.API_URL,{auth:{token},transports:['websocket','polling']});socket.on('connect',()=>{els.onlineDot.classList.add('online');els.networkStatus.textContent='Connected';socket.emit('presence:hello')});socket.on('disconnect',()=>{els.onlineDot.classList.remove('online');els.networkStatus.textContent='Reconnecting'});socket.on('checkin:new',refresh);socket.on('visit:reviewed',refresh);socket.on('rtc:incoming',x=>{pendingCall=x;els.incomingName.textContent=`${x.fromName} is calling`;els.incomingDialog.showModal()});socket.on('rtc:answer',async x=>{if(pc&&x.callId===currentCallId)await pc.setRemoteDescription(x.answer)});socket.on('rtc:ice',async x=>{if(pc&&x.callId===currentCallId&&x.candidate)try{await pc.addIceCandidate(x.candidate)}catch{}});socket.on('rtc:declined',()=>endCall('Call declined'));socket.on('rtc:ended',()=>endCall('Call ended'));}
async function getMedia(){return navigator.mediaDevices.getUserMedia({video:{facingMode:facing},audio:{echoCancellation:true,noiseSuppression:true,autoGainControl:true}})}
function makePeer(targetId){pc=new RTCPeerConnection({iceServers});pc.onicecandidate=e=>e.candidate&&socket.emit('rtc:ice',{targetId,callId:currentCallId,candidate:e.candidate});pc.ontrack=e=>els.remoteVideo.srcObject=e.streams[0];pc.onconnectionstatechange=()=>{els.callState.textContent=pc.connectionState;if(['failed','closed'].includes(pc.connectionState))endCall('Connection ended')};callStream.getTracks().forEach(t=>pc.addTrack(t,callStream));return pc;}
async function startCall(targetId){if(!targetId)return alert('Select a person to call.');try{currentPeer=targetId;currentCallId=crypto.randomUUID();callStream=await getMedia();els.localVideo.srcObject=callStream;els.callDialog.showModal();els.callState.textContent='Calling';makePeer(targetId);const offer=await pc.createOffer();await pc.setLocalDescription(offer);socket.emit('rtc:call',{targetId,callId:currentCallId,offer});}catch(e){endCall(e.message);}}
els.parentCallBtn.onclick=()=>startCall(els.parentCallTarget.value);els.workerCallBtn.onclick=()=>startCall(els.workerCallTarget.value);els.acceptBtn.onclick=async()=>{try{const x=pendingCall;pendingCall=null;currentPeer=x.fromId;currentCallId=x.callId;callStream=await getMedia();els.localVideo.srcObject=callStream;els.incomingDialog.close();els.callDialog.showModal();makePeer(currentPeer);await pc.setRemoteDescription(x.offer);const answer=await pc.createAnswer();await pc.setLocalDescription(answer);socket.emit('rtc:answer',{targetId:currentPeer,callId:currentCallId,answer});els.callState.textContent='Connected';}catch(e){endCall(e.message)}};els.declineBtn.onclick=()=>{if(pendingCall)socket.emit('rtc:decline',{targetId:pendingCall.fromId,callId:pendingCall.callId});pendingCall=null;els.incomingDialog.close()};els.hangupBtn.onclick=()=>{if(currentPeer)socket.emit('rtc:end',{targetId:currentPeer,callId:currentCallId});endCall('Call ended')};function endCall(msg=''){try{pc?.close()}catch{}callStream?.getTracks().forEach(t=>t.stop());pc=null;callStream=null;els.localVideo.srcObject=null;els.remoteVideo.srcObject=null;currentPeer=null;currentCallId=null;els.callMsg.textContent=msg;if(els.callDialog.open)els.callDialog.close();}
els.micBtn.onclick=()=>{const t=callStream?.getAudioTracks()[0];if(t){t.enabled=!t.enabled;els.micBtn.textContent=t.enabled?'Mute':'Unmute'}};els.camBtn.onclick=()=>{const t=callStream?.getVideoTracks()[0];if(t){t.enabled=!t.enabled;els.camBtn.textContent=t.enabled?'Camera off':'Camera on'}};
async function openDevice(forCheck=false){try{deviceStream?.getTracks().forEach(t=>t.stop());deviceStream=await getMedia();els.preview.srcObject=deviceStream;els.deviceDialog.showModal();els.deviceMsg.textContent=forCheck?'Camera/mic verified. Close this panel after confirming your device works; the video itself is not saved.':'Camera and microphone are working. Nothing is uploaded.';}catch(e){els.deviceMsg.textContent=`Unable to open camera/mic: ${e.message}`}}
els.deviceBtn.onclick=()=>openDevice(false);els.switchCam.onclick=async()=>{facing=facing==='user'?'environment':'user';await openDevice(false)};document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>{const d=$(b.dataset.close);if(d===els.deviceDialog){deviceStream?.getTracks().forEach(t=>t.stop());deviceStream=null;els.preview.srcObject=null}d.close()});
function setupInstall(){window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstall=e});els.installBtn.onclick=async()=>{if(deferredInstall){deferredInstall.prompt();await deferredInstall.userChoice;deferredInstall=null;return}const ios=/iphone|ipad|ipod/i.test(navigator.userAgent);els.installSteps.innerHTML=ios?'<ol><li>Open this page in <b>Safari</b>.</li><li>Tap the <b>Share</b> button.</li><li>Scroll and choose <b>Add to Home Screen</b>.</li><li>Tap <b>Add</b>.</li><li>Open the new icon and allow Location, Camera, Microphone, and Notifications when requested.</li></ol>':'<ol><li>Open this site in Chrome.</li><li>Tap the browser menu (⋮).</li><li>Choose <b>Install app</b> or <b>Add to Home screen</b>.</li><li>Confirm Install.</li></ol>';els.installDialog.showModal()}}
boot();
})();
