window.APP_CONFIG = {
  API_URL: "https://YOUR-RENDER-SERVICE.onrender.com",
  VISIT_MINUTES: 120,
  CHECKIN_INTERVAL_MINUTES: 45,
  REMINDER_GRACE_MINUTES: 10,
  APP_NAME: "Family Visit Compliance"
};
